Update xg-040g-md.yml

diff --git a/.github/workflows/xg-040g-md.yml b/.github/workflows/xg-040g-md.yml
--- a/.github/workflows/xg-040g-md.yml
+++ b/.github/workflows/xg-040g-md.yml
@@ -15,178 +15,176 @@ on:
         type: boolean
 
 env:
-  CONFIG_FILE: 'config/xg-040g-md.config'
+  CONFIG_FILE: "config/xg-040g-md.config"
   # REPO_URL: https://github.com/immortalwrt/immortalwrt.git
   REPO_URL: https://github.com/openwrt/openwrt.git
   REPO_BRANCH: openwrt-25.12
-  FEEDS_CONF: feeds.conf.default
   UPLOAD_FIRMWARE: true
   UPLOAD_RELEASE: true
   TZ: Asia/Shanghai
-  
+
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@master
+      - name: Checkout
+        uses: actions/checkout@master
 
-    - name: Cleanup disk space
-      run: |
-        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
-        sudo docker image prune -a -f
-        sudo apt-get update
-        sudo apt-get remove -y '^dotnet-.*' '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' azure-cli google-cloud-sdk mono-devel powershell firefox
-        sudo apt-get autoremove -y
-        sudo apt-get clean
+      - name: Cleanup disk space
+        run: |
+          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
+          sudo docker image prune -a -f
+          sudo apt-get update
+          sudo apt-get remove -y '^dotnet-.*' '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' azure-cli google-cloud-sdk mono-devel powershell firefox
+          sudo apt-get autoremove -y
+          sudo apt-get clean
 
-    - name: Initialization environment
-      id: init
-      env:
-        DEBIAN_FRONTEND: noninteractive
-      run: |
-        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
-        sudo docker image prune -a -f
-        sudo apt-get remove -y '^dotnet-.*' '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' azure-cli google-cloud-sdk mono-devel powershell firefox
-        sudo apt-get autoremove -y
-        sudo apt-get clean
-        sudo apt-get update
-        sudo apt-get install -y \
-        build-essential clang flex bison g++ gawk gettext \
-        git libncurses-dev libssl-dev python3-dev python3-setuptools \
-        python3-pyelftools swig rsync unzip zlib1g-dev file wget \
-        bc libelf-dev qemu-utils mkbootimg device-tree-compiler
-        # 验证安装
-        mkbootimg --help || true
-        MKBOOTIMG_PATH=$(which mkbootimg)
-        if [ -n "$MKBOOTIMG_PATH" ]; then
-        echo "mkbootimg found at: $MKBOOTIMG_PATH"
-        file "$MKBOOTIMG_PATH"
-        else
-        echo "❌ mkbootimg not found in PATH!"
-        fi
-        
-        sudo timedatectl set-timezone "${TZ}"
-        echo "status=success" >> ${GITHUB_OUTPUT}
-        
-    - name: Ensure Python build tools
-      run: |
-        python3 -m pip install --upgrade pip setuptools wheel
-        python3 -m pip --version
-        python3 -c "import setuptools.build_meta; print('setuptools.build_meta OK')"
-        python3 -m pip install Unidecode
-        
-        
-    - name: Clone source code
-      id: codes
-      if: steps.init.outputs.status == 'success' && success()
-      run: |
-        git clone --depth 1 "$REPO_URL" -b "$REPO_BRANCH" openwrt
-        if [ -n "$GITHUB_OUTPUT" ]; then
-        echo "status=success" >> "$GITHUB_OUTPUT"
-        else
-        echo "::set-output name=status::success"
-        fi
-       
-    - name: Free up disk space
-      run: |
-        sudo mkdir -p /mnt/openwrt/{dl,staging_dir,build_dir}
-        sudo chown -R $USER:$GROUPS /mnt/openwrt
-        ln -sfn /mnt/openwrt/dl openwrt/dl
-        ln -sfn /mnt/openwrt/staging_dir openwrt/staging_dir
-        ln -sfn /mnt/openwrt/build_dir openwrt/build_dir
-        df -H
+      - name: Initialization environment
+        id: init
+        env:
+          DEBIAN_FRONTEND: noninteractive
+        run: |
+          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
+          sudo docker image prune -a -f
+          sudo apt-get remove -y '^dotnet-.*' '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' azure-cli google-cloud-sdk mono-devel powershell firefox
+          sudo apt-get autoremove -y
+          sudo apt-get clean
+          sudo apt-get update
+          sudo apt-get install -y \
+          build-essential clang flex bison g++ gawk gettext \
+          git libncurses-dev libssl-dev python3-dev python3-setuptools \
+          python3-pyelftools swig rsync unzip zlib1g-dev file wget \
+          bc libelf-dev qemu-utils mkbootimg device-tree-compiler
+          # 验证安装
+          mkbootimg --help || true
+          MKBOOTIMG_PATH=$(which mkbootimg)
+          if [ -n "$MKBOOTIMG_PATH" ]; then
+          echo "mkbootimg found at: $MKBOOTIMG_PATH"
+          file "$MKBOOTIMG_PATH"
+          else
+          echo "❌ mkbootimg not found in PATH!"
+          fi
 
-    - name: Update & Install feeds
-      working-directory: ./openwrt
-      run: |
-        sed -i '/routing/d' feeds.conf.default
-        sed -i '/telephony/d' feeds.conf.default
-        ./scripts/feeds update -a
-        ./scripts/feeds install -a -f
+          sudo timedatectl set-timezone "${TZ}"
+          echo "status=success" >> ${GITHUB_OUTPUT}
 
-    - name: Configuration Customization
-      run: |
-      
-        cp -fv "${CONFIG_FILE}" openwrt/.config
-        cd openwrt && make defconfig
-      
-    - name: 自动上传编译配置
-      uses: actions/upload-artifact@v4
-      with:
-       name: build-config
-       path: |
-        openwrt/.config
-        openwrt/feeds.conf.default
-      
-    - name: Download package
-      working-directory: ./openwrt
-      run: |
-        make download -j4 V=s
-        find dl -size -1024c -delete
+      - name: Ensure Python build tools
+        run: |
+          python3 -m pip install --upgrade pip setuptools wheel
+          python3 -m pip --version
+          python3 -c "import setuptools.build_meta; print('setuptools.build_meta OK')"
+          python3 -m pip install Unidecode
 
-    - name: Compile the OpenWrt
-      id: compile
-      run: |
-        cd openwrt/
-        make defconfig
-        if [[ "${{ inputs.log_switch }}" == "true" ]]; then
-            make -j1 V=s
-        else
-            make -j$(nproc)
-        fi
-        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
-        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
-        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
-        echo "status=success" >> $GITHUB_OUTPUT
-        
-    - name: Organize files
-      id: organize
-      if: env.UPLOAD_FIRMWARE == 'true' && steps.compile.outputs.status == 'success'
-      run: |
-        cd openwrt/bin/targets/*/*
-        rm -rf packages
-        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
-        echo "status=success" >> $GITHUB_OUTPUT
+      - name: Clone source code
+        id: codes
+        if: steps.init.outputs.status == 'success' && success()
+        run: |
+          git clone --depth 1 "$REPO_URL" -b "$REPO_BRANCH" openwrt
+          if [ -n "$GITHUB_OUTPUT" ]; then
+          echo "status=success" >> "$GITHUB_OUTPUT"
+          else
+          echo "::set-output name=status::success"
+          fi
 
-    - name: Upload firmware directory
-      uses: actions/upload-artifact@main
-      if: steps.organize.outputs.status == 'success' && !cancelled()
-      with:
-        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
-        path: ${{ env.FIRMWARE }}/*
+      - name: Free up disk space
+        run: |
+          sudo mkdir -p /mnt/openwrt/{dl,staging_dir,build_dir}
+          sudo chown -R $USER:$GROUPS /mnt/openwrt
+          ln -sfn /mnt/openwrt/dl openwrt/dl
+          ln -sfn /mnt/openwrt/staging_dir openwrt/staging_dir
+          ln -sfn /mnt/openwrt/build_dir openwrt/build_dir
+          df -H
 
-    - name: Generate release tag
-      id: tag
-      if: env.UPLOAD_RELEASE == 'true' && steps.organize.outputs.status == 'success'
-      run: |
-        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
-        cat <<EOF > release.txt
-        🚀 OpenWrt firmware for XG-040G-MD
-        ----------------------
-        设备型号: BELL XG-040G-MD
-        构建时间: $(date +"%Y-%m-%d %H:%M")
-        内核版本: 6.12.X
-        源码仓库: $REPO_URL
-        分支: $REPO_BRANCH
-        EOF
-        echo "status=success" >> $GITHUB_OUTPUT
+      - name: Update & Install feeds
+        working-directory: ./openwrt
+        run: |
+          sed -i '/routing/d' feeds.conf.default
+          sed -i '/telephony/d' feeds.conf.default
+          sed -i '/video/d' feeds.conf.default
+          ./scripts/feeds update -a
+          ./scripts/feeds install -a -f
 
-    - name: Publish GitHub Release
-      uses: ncipollo/release-action@v1
-      with:
-        tag: ${{ steps.tag.outputs.release_tag }}
-        bodyFile: release.txt
-        artifacts: |
-          ${{ env.FIRMWARE }}/*
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Configuration Customization
+        run: |
+          cp -fv "${CONFIG_FILE}" openwrt/.config
+          cd openwrt && make defconfig
 
-    - name: Cleanup workflow runs
-      uses: Mattraks/delete-workflow-runs@v2
-      with:
-        retain_days: 7
-        keep_minimum_runs: 5
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: 自动上传编译配置
+        uses: actions/upload-artifact@v4
+        with:
+          name: build-config
+          path: |
+            openwrt/.config
+            openwrt/feeds.conf.default
+
+      - name: Download package
+        working-directory: ./openwrt
+        run: |
+          make download -j4 V=s
+          find dl -size -1024c -delete
+
+      - name: Compile the OpenWrt
+        id: compile
+        run: |
+          cd openwrt/
+          make defconfig
+          if [[ "${{ inputs.log_switch }}" == "true" ]]; then
+              make -j1 V=s
+          else
+              make -j$(nproc)
+          fi
+          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
+          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
+          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
+          echo "status=success" >> $GITHUB_OUTPUT
+
+      - name: Organize files
+        id: organize
+        if: env.UPLOAD_FIRMWARE == 'true' && steps.compile.outputs.status == 'success'
+        run: |
+          cd openwrt/bin/targets/*/*
+          rm -rf packages
+          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
+          echo "status=success" >> $GITHUB_OUTPUT
+
+      - name: Upload firmware directory
+        uses: actions/upload-artifact@main
+        if: steps.organize.outputs.status == 'success' && !cancelled()
+        with:
+          name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
+          path: ${{ env.FIRMWARE }}/*
+
+      - name: Generate release tag
+        id: tag
+        if: env.UPLOAD_RELEASE == 'true' && steps.organize.outputs.status == 'success'
+        run: |
+          echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
+          cat <<EOF > release.txt
+          🚀 OpenWrt firmware for XG-040G-MD
+          ----------------------
+          设备型号: NOKIA BELL XG-040G-MD
+          构建时间: $(date +"%Y-%m-%d %H:%M")
+          内核版本: 6.12.X
+          源码仓库: $REPO_URL
+          分支: $REPO_BRANCH
+          EOF
+          echo "status=success" >> $GITHUB_OUTPUT
+
+      - name: Publish GitHub Release
+        uses: ncipollo/release-action@v1
+        with:
+          tag: ${{ steps.tag.outputs.release_tag }}
+          bodyFile: release.txt
+          artifacts: |
+            ${{ env.FIRMWARE }}/*
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Cleanup workflow runs
+        uses: Mattraks/delete-workflow-runs@v2
+        with:
+          retain_days: 7
+          keep_minimum_runs: 5
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
